all: RaceCond RaceCondT RaceCondS RaceCondM

RaceCond:
	gcc RaceCond.c -o RaceCond -lpthread

RaceCondT:
	gcc RaceCondT.c -o RaceCondT -lpthread

RaceCondS:
	gcc RaceCondS.c -o RaceCondS -lpthread

RaceCondM:
	gcc RaceCondM.c -o RaceCondM -lpthread

clean:
	rm RaceCond RaceCondT RaceCondS RaceCondM
