all: RaceCond RaceCond2 RaceCondT RaceCondTB RaceCondS RaceCondM

RaceCond:
	gcc RaceCond.c -o RaceCond -lpthread

RaceCond2:
	gcc RaceCond2.c -o RaceCond2 -lpthread

RaceCondT:
	gcc RaceCondT.c -o RaceCondT -lpthread

RaceCondTB:
	gcc RaceCondTB.c -o RaceCondTB -lpthread

RaceCondS:
	gcc RaceCondS.c -o RaceCondS -lpthread

RaceCondM:
	gcc RaceCondM.c -o RaceCondM -lpthread

clean:
	rm RaceCond RaceCond2 RaceCondT RaceCondTB RaceCondS RaceCondM
